action.configuration.commerce_marketplace_mark_as_default:
  type: action_configuration_default
  label: 'Configuration for the Mark as default action'

action.configuration.commerce_marketplace_mark_as_owner_default:
  type: action_configuration_default
  label: 'Configuration for the Mark as owner default action'

action.configuration.commerce_marketplace_clear_owner_store_limit:
  type: action_configuration_default
  label: 'Configuration for the Clear owner store type limit action'

action.configuration.commerce_marketplace_clear_store_type_limit:
  type: action_configuration_default
  label: 'Configuration for the Clear store type limit action'

action.configuration.commerce_marketplace_increase_owner_limit_by_one:
  type: action_configuration_default
  label: 'Configuration for the Increase owner store type limit by one action'

action.configuration.commerce_marketplace_increase_store_limit_by_one:
  type: action_configuration_default
  label: 'Configuration for the Increase store type limit by one action'

action.configuration.commerce_marketplace_set_owner_limit_to_one:
  type: action_configuration_default
  label: 'Configuration for the Set owner store type limit to one action'

action.configuration.commerce_marketplace_set_store_limit_to_one:
  type: action_configuration_default
  label: 'Configuration for the Set store type limit to one action'

field.formatter.settings.commerce_marketplace_type_label:
  type: config_object
  label: 'Marketplace type formatter settings'
  mapping:
    link:
      type: integer
      label: 'Link to the store type entity'

field.formatter.settings.commerce_marketplace_name:
  type: config_object
  label: 'Marketplace name formatter settings'
  mapping:
    link_to_entity:
      type: integer
      label: 'Link to the entity'

marketplace_compact_formatter:
  type: config_object
  mapping:
    link:
      type: integer
      label: 'Link label to the entity'
    summary:
      type: string
      label: 'Summary title'
    empty:
      type: string
      label: 'Empty list placeholder'
    open:
      type: boolean
      label: 'Whether to show details element expanded by default'
    list:
      type: string
      label: 'List style'
    separator:
      type: string
      label: 'The separator for the simple inline list items'
    max:
      type: string
      label: 'The maximum number of labels to display'
    offset:
      type: string
      label: 'The offset where to start labels to display'

field.formatter.settings.commerce_marketplace_label_compact:
  type: marketplace_compact_formatter
  label: 'Marketplace label compact formatter settings'

field.formatter.settings.commerce_marketplace_list_compact:
  type: marketplace_compact_formatter
  label: 'Marketplace list options compact formatter settings'

marketplace_store_types:
  type: sequence
  label: 'Marketplace types'
  sequence:
    type: mapping
    label: 'Marketplace type'
    mapping:
      limit:
        type: integer
        label: 'Marketplace type limit'

commerce_marketplace.settings:
  type: config_object
  label: 'Commerce Multitore settings'
  mapping:
    owners:
      type: sequence
      label: 'Marketplace owners'
      sequence:
        type: mapping
        label: 'Marketplace owner'
        mapping:
          default_store:
            type: string
            label: 'Marketplace owner default store'
          store_types:
            type: marketplace_store_types
    store_types:
      type: marketplace_store_types
